---
- name:  hipops playbook
  hosts: "{{ inventory }}"
  tasks:
    - include: tasks/sync-repository.yml dest="{{ dest }}" repository="{{ repository | default("null") }}"
    - include: tasks/copy-files.yml files="{{ files | default("null") }}"
    - include: tasks/docker.yml containers="{{ containers }}"
